language: php

sudo: false

jobs:
  include:
  - dist: trusty
    php: 5.4
  - dist: trusty
    php: 5.5
  - dist: xenial
    php: 5.6
  - dist: xenial
    php: 7.0
  - dist: xenial
    php: 7.1
  - dist: xenial
    php: 7.2
  - dist: xenial
    php: 7.3
  - dist: xenial
    php: 7.4
  - dist: xenial
    php: nightly
  - dist: xenial
    php: hhvm
  allow_failures:
    - php: nightly
    - php: hhvm

before_script:
  - printf "\n" | pecl install imagick
  - composer self-update || true
  - composer install --prefer-dist --no-interaction --no-progress --no-suggest --optimize-autoloader

script: vendor/bin/phpunit
